### PR TITLE
#184 Overwrite/Update existing session. Added 'Replace with current w…

### PR DESCRIPTION
**Pull request by mrwensveen**
#184 Added 'Replace with current window' option

### CODE REVIEW

**Comment by mrwensveen** [comment]
I'm not very proficient with git and GitHub yet, so let me know if I should do things differently.

**Comment by sienori** [comment]
Great!

Just one thing:
Only `_locales/en/messages.json` needs updating `message.json`.
Please delete updates of `af_ZA`, `ar_SA` and other languages (Excluding `en`).
Update of other languages ​​is done through Crowdin.

Thank you for your contribution!

**Comment by mrwensveen** [comment]
Okay. Is there a smart way to do this with git? I could just remove the lines and commit/push again, but maybe I can amend the commit and pull request?

**Comment by mrwensveen** [comment]
I think I pulled it off, somehow. I pushed and pulled and rebased and reverted and amended and I think it worked... maybe? Or maybe I broke the whole thing and I need to start over?

**Comment by sienori** [comment]
Perfect! I really appreciate it!!

**Pull request merged**
