### PR TITLE
Add Group Information to Tracking

### PR DESCRIPTION
**Pull request by TheOverpassArsonist**
Adds tab group information to the tracking updates to prevent them from being wiped, fix for issue #1136 

I've programmed a bit as a hobby but this is my first time doing any javascript and first time using git at all really so, while I did some testing and it seemed to work, there is a non-zero chance I've missed something here. If I have then I likely won't be able to help much in pinning the issue down.

### CODE REVIEW

**Comment by Ziip-dev** [comment]
Maybe you can assign the repo owner (@sienori) as a reviewer for this PR so we can have a feedback on the proposed changes?

**Comment by Ziip-dev** [comment]
Yes, I tried creating an issue to check that and you're right: the permission is not granted by default.
So we just have to hope that @sienori can have a look on your PR soon, it seems that the last interactions on PRs date back to early September.

**Comment by sienori** [comment]
Thank you for the pull request, and I apologize for the long wait. The issue of tab groups not being saved in the tracking session was an oversight on my part. I will include this fix in the next version.

**Comment by Ziip-dev** [comment]
This officially makes your extension the _best browser extension ever_!
I'll definitely consider a donation now that I know the project is not abandoned and given how much it helps me with my "compulsive-tab-opening-disorder"! My computer's browser and I thank you for your work :)

**Comment by ngirard** [comment]
Hey @sienori,
thank you so much for your dedication and this new release !
Cheers !

**Pull request merged**
