### PR TITLE
Save only current tab

### LINKED ISSUE #379: Add a Single Tab to a Saved Session!
**Is your feature request related to a problem? Please describe.**
It's annoying and highly inefficient, if I have a Window with a lot of tabs open and saving the Session(Window) to then have to go through and delete each individual tab that I do not wish to be part of my saved Session. It is also equally inefficient to have to open a new window and drag all the tabs I want saved, to a new Window to be saved as a Session.

**Describe the solution you'd like**
The simplest way to fix this is to add the option to add any single tab to any session they please.

**Describe alternatives you've considered**
Alternative things I've considered is using different Session Managers. Another issue with Tab Session Manager is the possibility have duplicate saves, it'd be nice to not save any duplicate tabs.

**Additional context**
https://i.imgur.com/XJ3LLkR.png
In this screenshot you'll notice a context menu made for One Tab, it has the ability to save a single tab. Something like this would be extremely useful. Also if you get the chance, I'd take a look at Session Sync @sienori  to get a few more ideas of some things you can add to Tab Session Manager to make it the best Session Manager around. I currently use multiple Session Managers because some do more than others. I find this to be inefficient so a single Manager that could do it all what would be worth it.

### PR DESCRIPTION
**Pull request by aunpyz**
I'm not sure if this change gonna fix #379, but this is the feature that I really want myself 😊
So please feel free to edit this message if it's not relevant to #379.

Firefox
firefox
Chromium
chromium

### CODE REVIEW

**Comment by bwbohl** [comment]
I think this is a great idea

**Comment by Anutrix** [comment]
Why is this still unmerged? Any issues or comments?

**Comment by aunpyz** [comment]
I don't know, I opened it since it has no conflicts but I'm no longer using this extension after I waited for response from maintainer for months😕

**Comment by sienori** [comment]
I apologize for the very late reply. I could not merge this because the commit contains an unnecessary diff on locale.

**Pull request closed without merging**
