### PR TITLE
Enables up/down key navigation in session list

### PR DESCRIPTION
**Pull request by potockyt**
It has been bothering me for some time that while I could open the extension with list of sessions by shortcut, I had to use mouse to actually select and open session, or go through numerous elements using TAB key. This code should allow selecting and opening of session using up/down/enter keys.

I'm neither reactjs nor javascript developer so the code may not be up to your standards, tough this functionality is something that would be nice to add.

### CODE REVIEW

**Comment by sienori** [comment]
Thank you for the pull request!

The proposed feature seems useful. But we have to remember that there are users who use screen readers. If the session is opened by pressing the enter key, they will be confused. Therefore, the request cannot be accepted at this time.

The idea to correct order of focus in the session list is great! (Using prev and next)
I will implement it partially.

**Comment by potockyt** [comment]
How about using modifier `Shift+Enter` or `Ctrl+Enter` to open selected session, would that be a problem too?

Thanks for implementing the idea!

**Comment by sienori** [comment]
`Shift+Enter` is a good idea!
I implemented key navigation. https://github.com/sienori/Tab-Session-Manager/commit/005e7e6b0619bd41cfa56fe4fb8c0a38f5b2c862 https://github.com/sienori/Tab-Session-Manager/commit/3371f75e4f6002c811c9c24df1b0ebbd2f0c75e6
Your suggestion made the Tab Session Manager a more convenient extension.
Thank you!!

**Comment by potockyt** [comment]
Excellent, keep up the good work!

**Pull request closed without merging**
